<?php
$lang = array(
	'title' => 'The Burning Fox',
	'info' =>
		'Our security agency got delivered a copy of a portable firefox installation.<br/>'.
		'Your job is to crack the master password so the authorities can investigate more websites and private content generated by this person.<br/>'.
		'You can download the portable version from this folder, filename &quot;burningfox.zip&quot;.<br/>'.
		'<br/>'.
		'Good Luck!',
);
?>