<?php
/**
 * Auto Generated by GWF3 *
 * It is good to have a backup at a second physical location *
 * Because of the GWF_SECRET_SALT *
 */
#######################
### Error reporting ###
#######################
ini_set('display_errors', 1);
error_reporting(0xffffffff);

###################
### Main Config ###
###################
define('GWF_DOMAIN', 'localhost'); # HOSTNAME?
define('GWF_SITENAME', 'GWF3');  # any string: sitename
define('GWF_WEB_ROOT_NO_LANG', '/'); # usually / or /GWF/

##########################
### 3rd Party GPL Code ###
##########################
define('GWF_GESHI_PATH', '/data/_ProjectPDT2/geshi/geshi.php'); # GeSHi - Generic Syntax Highlighter
define('GWF_SMARTY_PATH', '/data/_ProjectPDT5/GWF33/core/inc3p/smarty/Smarty.class.php'); # Smarty - Template Engine
define('GWF_JPGRAPH_PATH', '/date/_ProjectPDT2/jphraph/jpgraph.php'); # JPGraph - 

################
### Defaults ###
################
define('GWF_DEFAULT_URL', 'login'); # Default 1st URL ()
define('GWF_DEFAULT_LANG', 'en'); # Default language should be english
define('GWF_DEFAULT_MODULE', 'Login'); # Default 1st Module ()
define('GWF_DEFAULT_METHOD', 'Form'); # Default 1st Method  ()
define('GWF_DEFAULT_DESIGN', 'default'); # Default Design (default)

################
### Language ###
################
define('GWF_LANG_ADMIN', 'en'); # Admin language should be english
define('GWF_SUPPORTED_LANGS', 'en;de;fr;it;pl;hu;es;bs;et;fi;ur;tr;sq;nl;ru;cs;sr'); # All supported languages

###############
### Various ###
###############
define('GWF_ONLINE_TIMEOUT', 10); # A request will mark you online for N seconds
define('GWF_CRONJOB_BY_WEB', 0); # chance in permille to trigger www cronjob by client (0-1000)
define('GWF_CAPTCHA_COLOR_BG', 'FFFFFF');
define('GWF_USER_STACKTRACE', true); # Show a stacktrace to the user, if set.

##############################
### Database Configuration ###
##############################
define('GWF_SECRET_SALT', 'AAAABBBBCCCCDDDD'); # Changeme
define('GWF_CHMOD', 0700); # CHMOD mask for file creation. 0700 for mpm-itk env. 0777 in worst case
define('GWF_DB_HOST', 'localhost');
define('GWF_DB_USER', 'lamb3');
define('GWF_DB_PASSWORD', 'lamb3');
define('GWF_DB_DATABASE', 'lamb3');
define('GWF_DB_TYPE', 'mysql'); # currently only mysql is supported
define('GWF_DB_ENGINE', 'myISAM'); # innoDB or myISAM
define('GWF_TABLE_PREFIX', 'lamb3_'); # Change at will, dual install possible.

#############################
### Session/Cookie Config ###
#############################
define('GWF_SESS_NAME', 'GWF3'); # cookie name
define('GWF_SESS_SECURE', false); # cookie is ssl only
define('GWF_SESS_LIFETIME', 432000); # cookie lifetime
define('GWF_SESS_PER_USER', 3); # sessions max per user

###################
### IP Settings ###
###################
define('GWF_IP_QUICK', 'hash_32_1');  # Hashed IP Duplicates (see GWF_IP6.php)
define('GWF_IP_EXACT', 'bin_32_128'); # Complete IP storage (see GDO/IP6.php)

####################
### Email Config ###
####################
define('GWF_DEBUG_EMAIL', 0x0F); # 0=NONE, 1=DB ERRORS, 2=PHP_ERRORS, 4=404, 8=403
define('GWF_BOT_EMAIL', 'robot@giz.org');
define('GWF_ADMIN_EMAIL', 'gizmore@giz.org');
define('GWF_STAFF_EMAILS', ''); # separate cc plain emails by, (not really used yet)
define('GWF_SUPPORT_EMAIL', 'support@giz.org'); # all staff members should catch those

#####################
### Website Down? ###
#####################
require_once 'protected/temp_ban.php';
require_once 'protected/temp_down.php';
?>
