<!DOCTYPE html>
<html>
<head>
	<title>[WeChall] WeChall</title>
	<meta name="robots" content="index, follow" />
	<meta name="keywords" content="Hackit, Challenge, Problem, Riddle, WeChall, Global, Hacker, Webseite, Ranking, Rätsel, Herrausforderung, Computer, Knacken, Hacken, Cracken, Stegano, Cryptography, Exploit, Training">
	<meta name="description" content="Eine Übersicht der Hackit-, Rätsel- und Problemlösungs Seiten - WeChall">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	
	<meta name="generator" content="GWFv3.04-2012.Jul.01" />
	<link rel="stylesheet" type="text/css" href="/tpl/default/css/gwf3.css?v=57" />
	<link rel="stylesheet" type="text/css" href="/tpl/wc4/css/wechall4.css?v=57" />
</head>
<body>
<a href="/about_wechall" id="wc_logo" title="WeChall"></a>
<h1>User of the month!</h1>
<p>The algorithm only sums &quot;gain&quot; events. So linking a site does not count, and also only points are accumulated when the users were linked at the moment.</p>
<p>Do not take this too serious.</p>
<p>There is no gain_score available before August 2010.</p>
<table><thead><tr><th>2010 Aug</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/LeCanard">LeCanard</a></td><td>19382</td></tr><tr><td><a href="/profile/peterkodo">peterkodo</a></td><td>15920</td></tr><tr><td><a href="/profile/lordOric">lordOric</a></td><td>13047</td></tr><tr><td><a href="/profile/Stack">Stack</a></td><td>8584</td></tr><tr><td><a href="/profile/phoenix1204">phoenix1204</a></td><td>6538</td></tr></tbody></table>
<table><thead><tr><th>2010 Sep</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/totoiste">totoiste</a></td><td>16607</td></tr><tr><td><a href="/profile/flipp">flipp</a></td><td>16093</td></tr><tr><td><a href="/profile/SealX">SealX</a></td><td>12941</td></tr><tr><td><a href="/profile/PPatak">PPatak</a></td><td>12864</td></tr><tr><td><a href="/profile/kev1">kev1</a></td><td>12685</td></tr></tbody></table>
<table><thead><tr><th>2010 Oct</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/dloser">dloser</a></td><td>26019</td></tr><tr><td><a href="/profile/knauel">knauel</a></td><td>21530</td></tr><tr><td><a href="/profile/tripleedged">tripleedged</a></td><td>18164</td></tr><tr><td><a href="/profile/yachoor">yachoor</a></td><td>17989</td></tr><tr><td><a href="/profile/guybrush1112">guybrush1112</a></td><td>14691</td></tr></tbody></table>
<table><thead><tr><th>2010 Nov</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/DrArcheh">DrArcheh</a></td><td>31163</td></tr><tr><td><a href="/profile/tripleedged">tripleedged</a></td><td>29653</td></tr><tr><td><a href="/profile/Jinx">Jinx</a></td><td>19914</td></tr><tr><td><a href="/profile/CHItA">CHItA</a></td><td>16848</td></tr><tr><td><a href="/profile/steven18">steven18</a></td><td>15209</td></tr></tbody></table>
<table><thead><tr><th>2010 Dec</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td>unknown</td><td>27575</td></tr><tr><td><a href="/profile/PHmaster">PHmaster</a></td><td>20066</td></tr><tr><td><a href="/profile/CHItA">CHItA</a></td><td>18547</td></tr><tr><td><a href="/profile/pixelie">pixelie</a></td><td>17015</td></tr><tr><td><a href="/profile/grimskies">grimskies</a></td><td>16638</td></tr></tbody></table>
<table><thead><tr><th>2011 Jan</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/adkatrit">adkatrit</a></td><td>66156</td></tr><tr><td><a href="/profile/sysfail">sysfail</a></td><td>27450</td></tr><tr><td><a href="/profile/Ens">Ens</a></td><td>26489</td></tr><tr><td><a href="/profile/shadum">shadum</a></td><td>23159</td></tr><tr><td><a href="/profile/kithyane">kithyane</a></td><td>21846</td></tr></tbody></table>
<table><thead><tr><th>2011 Feb</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/dloser">dloser</a></td><td>58676</td></tr><tr><td><a href="/profile/AliceInDilbertland">AliceInDilbertland</a></td><td>47959</td></tr><tr><td><a href="/profile/yachoor">yachoor</a></td><td>26970</td></tr><tr><td><a href="/profile/sabretooth">sabretooth</a></td><td>22767</td></tr><tr><td><a href="/profile/Matyt">Matyt</a></td><td>20730</td></tr></tbody></table>
<table><thead><tr><th>2011 Mar</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/Caesum">Caesum</a></td><td>25705</td></tr><tr><td><a href="/profile/combinat">combinat</a></td><td>25438</td></tr><tr><td><a href="/profile/sabretooth">sabretooth</a></td><td>25159</td></tr><tr><td><a href="/profile/LoneWolf219">LoneWolf219</a></td><td>24725</td></tr><tr><td><a href="/profile/yachoor">yachoor</a></td><td>24708</td></tr></tbody></table>
<table><thead><tr><th>2011 Apr</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/IPYouFy">IPYouFy</a></td><td>86345</td></tr><tr><td><a href="/profile/xmadx">xmadx</a></td><td>37493</td></tr><tr><td><a href="/profile/Caesum">Caesum</a></td><td>28536</td></tr><tr><td><a href="/profile/xen">xen</a></td><td>25970</td></tr><tr><td><a href="/profile/tehron">tehron</a></td><td>24652</td></tr></tbody></table>
<table><thead><tr><th>2011 May</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/Mart">Mart</a></td><td>29302</td></tr><tr><td><a href="/profile/peterkodo">peterkodo</a></td><td>27552</td></tr><tr><td><a href="/profile/metodkar">metodkar</a></td><td>26171</td></tr><tr><td><a href="/profile/IPYouFy">IPYouFy</a></td><td>20447</td></tr><tr><td><a href="/profile/tehron">tehron</a></td><td>14239</td></tr></tbody></table>
<table><thead><tr><th>2011 Jun</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/dloser">dloser</a></td><td>23500</td></tr><tr><td>unknown</td><td>21053</td></tr><tr><td><a href="/profile/Jinx">Jinx</a></td><td>19233</td></tr><tr><td><a href="/profile/LoneWolf219">LoneWolf219</a></td><td>14202</td></tr><tr><td><a href="/profile/tehron">tehron</a></td><td>14065</td></tr></tbody></table>
<table><thead><tr><th>2011 Jul</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/digitalseraphim">digitalseraphim</a></td><td>43353</td></tr><tr><td><a href="/profile/DarkService">DarkService</a></td><td>31247</td></tr><tr><td><a href="/profile/noother">noother</a></td><td>21829</td></tr><tr><td>unknown</td><td>20471</td></tr><tr><td><a href="/profile/RootMind">RootMind</a></td><td>15792</td></tr></tbody></table>
<table><thead><tr><th>2011 Aug</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/Chaosdreamer">Chaosdreamer</a></td><td>19799</td></tr><tr><td><a href="/profile/lordOric">lordOric</a></td><td>16849</td></tr><tr><td><a href="/profile/dloser">dloser</a></td><td>14581</td></tr><tr><td><a href="/profile/SatUrN">SatUrN</a></td><td>14338</td></tr><tr><td><a href="/profile/vs4vijay">vs4vijay</a></td><td>14147</td></tr></tbody></table>
<table><thead><tr><th>2011 Sep</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/IPYouFy">IPYouFy</a></td><td>30279</td></tr><tr><td><a href="/profile/peterkodo">peterkodo</a></td><td>15241</td></tr><tr><td><a href="/profile/Zathuros">Zathuros</a></td><td>14582</td></tr><tr><td><a href="/profile/awe">awe</a></td><td>14575</td></tr><tr><td><a href="/profile/metodkar">metodkar</a></td><td>13755</td></tr></tbody></table>
<table><thead><tr><th>2011 Oct</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/Zathuros">Zathuros</a></td><td>151441</td></tr><tr><td><a href="/profile/Luxerails">Luxerails</a></td><td>43968</td></tr><tr><td><a href="/profile/peterkodo">peterkodo</a></td><td>37044</td></tr><tr><td><a href="/profile/phoenix1204">phoenix1204</a></td><td>28596</td></tr><tr><td><a href="/profile/metodkar">metodkar</a></td><td>24305</td></tr></tbody></table>
<table><thead><tr><th>2011 Nov</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/joek">joek</a></td><td>53652</td></tr><tr><td><a href="/profile/pshyphon">pshyphon</a></td><td>39565</td></tr><tr><td><a href="/profile/gijsh">gijsh</a></td><td>33169</td></tr><tr><td><a href="/profile/phoenix1204">phoenix1204</a></td><td>25146</td></tr><tr><td><a href="/profile/shadum">shadum</a></td><td>24997</td></tr></tbody></table>
<table><thead><tr><th>2011 Dec</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/kwisatz">kwisatz</a></td><td>65669</td></tr><tr><td><a href="/profile/MrKaLiMaN">MrKaLiMaN</a></td><td>34945</td></tr><tr><td><a href="/profile/peterkodo">peterkodo</a></td><td>28258</td></tr><tr><td><a href="/profile/livinskull">livinskull</a></td><td>22242</td></tr><tr><td><a href="/profile/bobko">bobko</a></td><td>18077</td></tr></tbody></table>
<table><thead><tr><th>2012 Jan</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/grimskies">grimskies</a></td><td>45812</td></tr><tr><td><a href="/profile/benito255">benito255</a></td><td>35610</td></tr><tr><td><a href="/profile/Mawekl">Mawekl</a></td><td>28439</td></tr><tr><td><a href="/profile/ynori7">ynori7</a></td><td>22892</td></tr><tr><td>unknown</td><td>21189</td></tr></tbody></table>
<table><thead><tr><th>2012 Feb</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/benito255">benito255</a></td><td>39091</td></tr><tr><td><a href="/profile/Mart">Mart</a></td><td>34519</td></tr><tr><td><a href="/profile/martek">martek</a></td><td>23601</td></tr><tr><td>unknown</td><td>22040</td></tr><tr><td><a href="/profile/sabretooth">sabretooth</a></td><td>21594</td></tr></tbody></table>
<table><thead><tr><th>2012 Mar</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/kwisatz">kwisatz</a></td><td>33879</td></tr><tr><td><a href="/profile/vasis">vasis</a></td><td>29690</td></tr><tr><td>unknown</td><td>24838</td></tr><tr><td><a href="/profile/HiPhiSch">HiPhiSch</a></td><td>22944</td></tr><tr><td><a href="/profile/makler2004">makler2004</a></td><td>21967</td></tr></tbody></table>
<table><thead><tr><th>2012 Apr</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/Jos18">Jos18</a></td><td>45040</td></tr><tr><td><a href="/profile/Beat_Slayer">Beat_Slayer</a></td><td>26921</td></tr><tr><td><a href="/profile/panda73111">panda73111</a></td><td>26362</td></tr><tr><td><a href="/profile/brahim">brahim</a></td><td>20754</td></tr><tr><td><a href="/profile/faust">faust</a></td><td>20424</td></tr></tbody></table>
<table><thead><tr><th>2012 May</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/Beat_Slayer">Beat_Slayer</a></td><td>38907</td></tr><tr><td><a href="/profile/sine">sine</a></td><td>34228</td></tr><tr><td><a href="/profile/phoenix1204">phoenix1204</a></td><td>26624</td></tr><tr><td><a href="/profile/Hertz">Hertz</a></td><td>26623</td></tr><tr><td><a href="/profile/Posquit0">Posquit0</a></td><td>24637</td></tr></tbody></table>
<table><thead><tr><th>2012 Jun</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/MrKaLiMaN">MrKaLiMaN</a></td><td>26136</td></tr><tr><td><a href="/profile/phoenix1204">phoenix1204</a></td><td>24390</td></tr><tr><td><a href="/profile/GozuByt3s">GozuByt3s</a></td><td>18908</td></tr><tr><td><a href="/profile/faust">faust</a></td><td>16401</td></tr><tr><td><a href="/profile/korkinsson">korkinsson</a></td><td>14588</td></tr></tbody></table>
<table><thead><tr><th>2012 Jul</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/Mawekl">Mawekl</a></td><td>45533</td></tr><tr><td><a href="/profile/elasolova">elasolova</a></td><td>39626</td></tr><tr><td><a href="/profile/Luxerails">Luxerails</a></td><td>18501</td></tr><tr><td><a href="/profile/kwisatz">kwisatz</a></td><td>17007</td></tr><tr><td><a href="/profile/skdltmxn">skdltmxn</a></td><td>15802</td></tr></tbody></table>
<table><thead><tr><th>2012 Aug</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/kkoliver">kkoliver</a></td><td>23721</td></tr><tr><td><a href="/profile/bslime">bslime</a></td><td>19818</td></tr><tr><td><a href="/profile/deminase">deminase</a></td><td>17127</td></tr><tr><td><a href="/profile/kepten">kepten</a></td><td>16802</td></tr><tr><td><a href="/profile/hellsonic">hellsonic</a></td><td>16022</td></tr></tbody></table>
<table><thead><tr><th>2012 Sep</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/tunelko">tunelko</a></td><td>18019</td></tr><tr><td><a href="/profile/livinskull">livinskull</a></td><td>16651</td></tr><tr><td><a href="/profile/noother">noother</a></td><td>15013</td></tr><tr><td><a href="/profile/jnvb">jnvb</a></td><td>15000</td></tr><tr><td><a href="/profile/vasis">vasis</a></td><td>14816</td></tr></tbody></table>
<table><thead><tr><th>2012 Oct</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/Wixxerd">Wixxerd</a></td><td>34895</td></tr><tr><td><a href="/profile/poubin">poubin</a></td><td>23819</td></tr><tr><td><a href="/profile/sabretooth">sabretooth</a></td><td>22066</td></tr><tr><td><a href="/profile/Holographic">Holographic</a></td><td>21528</td></tr><tr><td><a href="/profile/SpArroW">SpArroW</a></td><td>17386</td></tr></tbody></table>
<table><thead><tr><th>2012 Nov</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td>unknown</td><td>47088</td></tr><tr><td><a href="/profile/Mawekl">Mawekl</a></td><td>42125</td></tr><tr><td><a href="/profile/Caesum">Caesum</a></td><td>40608</td></tr><tr><td><a href="/profile/Mart">Mart</a></td><td>36774</td></tr><tr><td><a href="/profile/stormsurfer">stormsurfer</a></td><td>30265</td></tr></tbody></table>
<table><thead><tr><th>2012 Dec</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/Hertz">Hertz</a></td><td>40340</td></tr><tr><td><a href="/profile/Caesum">Caesum</a></td><td>37627</td></tr><tr><td><a href="/profile/NLErwinC">NLErwinC</a></td><td>20263</td></tr><tr><td><a href="/profile/Jos18">Jos18</a></td><td>18215</td></tr><tr><td><a href="/profile/Mawekl">Mawekl</a></td><td>15376</td></tr></tbody></table>
<table><thead><tr><th>2013 Jan</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/skewlboy">skewlboy</a></td><td>45019</td></tr><tr><td><a href="/profile/benito255">benito255</a></td><td>40663</td></tr><tr><td><a href="/profile/Caesum">Caesum</a></td><td>28420</td></tr><tr><td>unknown</td><td>28039</td></tr><tr><td><a href="/profile/elasolova">elasolova</a></td><td>27328</td></tr></tbody></table>
<table><thead><tr><th>2013 Feb</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/dloser">dloser</a></td><td>66402</td></tr><tr><td><a href="/profile/ytbjplh">ytbjplh</a></td><td>52712</td></tr><tr><td><a href="/profile/sutupud">sutupud</a></td><td>41992</td></tr><tr><td><a href="/profile/benito255">benito255</a></td><td>37917</td></tr><tr><td><a href="/profile/ksydfius">ksydfius</a></td><td>31853</td></tr></tbody></table>
<table><thead><tr><th>2013 Mar</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/Gogil">Gogil</a></td><td>65303</td></tr><tr><td><a href="/profile/ytbjplh">ytbjplh</a></td><td>47846</td></tr><tr><td><a href="/profile/benito255">benito255</a></td><td>31366</td></tr><tr><td><a href="/profile/Mawekl">Mawekl</a></td><td>28035</td></tr><tr><td><a href="/profile/Mart">Mart</a></td><td>23069</td></tr></tbody></table>
<table><thead><tr><th>2013 Apr</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/badcob">badcob</a></td><td>72337</td></tr><tr><td><a href="/profile/Shrine">Shrine</a></td><td>34171</td></tr><tr><td><a href="/profile/xp45g">xp45g</a></td><td>26035</td></tr><tr><td><a href="/profile/kithyane">kithyane</a></td><td>23307</td></tr><tr><td><a href="/profile/skdltmxn">skdltmxn</a></td><td>22406</td></tr></tbody></table>
<table><thead><tr><th>2013 May</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/nurfed">nurfed</a></td><td>41233</td></tr><tr><td><a href="/profile/korkinsson">korkinsson</a></td><td>23087</td></tr><tr><td><a href="/profile/Chaosdreamer">Chaosdreamer</a></td><td>21527</td></tr><tr><td><a href="/profile/AhnMo">AhnMo</a></td><td>19361</td></tr><tr><td><a href="/profile/Mart">Mart</a></td><td>15198</td></tr></tbody></table>
<table><thead><tr><th>2013 Jun</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/LoneWolf219">LoneWolf219</a></td><td>27796</td></tr><tr><td><a href="/profile/AhnMo">AhnMo</a></td><td>18593</td></tr><tr><td><a href="/profile/Undr">Undr</a></td><td>18159</td></tr><tr><td><a href="/profile/xseris">xseris</a></td><td>16835</td></tr><tr><td><a href="/profile/dloser">dloser</a></td><td>16537</td></tr></tbody></table>
<table><thead><tr><th>2013 Jul</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/MrStorm">MrStorm</a></td><td>55979</td></tr><tr><td><a href="/profile/repnzscasb">repnzscasb</a></td><td>38649</td></tr><tr><td><a href="/profile/lavish">lavish</a></td><td>33141</td></tr><tr><td><a href="/profile/elasolova">elasolova</a></td><td>26763</td></tr><tr><td><a href="/profile/solarwind">solarwind</a></td><td>25862</td></tr></tbody></table>
<table><thead><tr><th>2013 Aug</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/MrStorm">MrStorm</a></td><td>34510</td></tr><tr><td><a href="/profile/nurfed">nurfed</a></td><td>26480</td></tr><tr><td><a href="/profile/Pzz_0">Pzz_0</a></td><td>25067</td></tr><tr><td><a href="/profile/phoenix1204">phoenix1204</a></td><td>23772</td></tr><tr><td><a href="/profile/rijman">rijman</a></td><td>23767</td></tr></tbody></table>
<table><thead><tr><th>2013 Sep</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/skdltmxn">skdltmxn</a></td><td>32110</td></tr><tr><td><a href="/profile/madbat2">madbat2</a></td><td>29632</td></tr><tr><td><a href="/profile/xp45g">xp45g</a></td><td>27914</td></tr><tr><td><a href="/profile/nurfed">nurfed</a></td><td>26924</td></tr><tr><td><a href="/profile/keidii">keidii</a></td><td>20294</td></tr></tbody></table>
<table><thead><tr><th>2013 Oct</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/madbat2">madbat2</a></td><td>37074</td></tr><tr><td><a href="/profile/Hertz">Hertz</a></td><td>29461</td></tr><tr><td><a href="/profile/nurfed">nurfed</a></td><td>28909</td></tr><tr><td><a href="/profile/jinmo123">jinmo123</a></td><td>28901</td></tr><tr><td>unknown</td><td>22567</td></tr></tbody></table>
<table><thead><tr><th>2013 Nov</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/jinmo123">jinmo123</a></td><td>42637</td></tr><tr><td><a href="/profile/tibbi">tibbi</a></td><td>41987</td></tr><tr><td><a href="/profile/Akorlith">Akorlith</a></td><td>35100</td></tr><tr><td><a href="/profile/apelord">apelord</a></td><td>29550</td></tr><tr><td><a href="/profile/mathpseudo">mathpseudo</a></td><td>28231</td></tr></tbody></table>
<table><thead><tr><th>2013 Dec</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/PopcornSecurity">PopcornSecurity</a></td><td>67681</td></tr><tr><td><a href="/profile/wasmaro">wasmaro</a></td><td>40936</td></tr><tr><td><a href="/profile/BlueH4G">BlueH4G</a></td><td>30912</td></tr><tr><td><a href="/profile/kev1">kev1</a></td><td>25990</td></tr><tr><td>unknown</td><td>25613</td></tr></tbody></table>
<table><thead><tr><th>2014 Jan</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/madbat2">madbat2</a></td><td>62434</td></tr><tr><td><a href="/profile/Holographic">Holographic</a></td><td>41655</td></tr><tr><td><a href="/profile/Apprentice56">Apprentice56</a></td><td>40497</td></tr><tr><td><a href="/profile/sabretooth">sabretooth</a></td><td>38223</td></tr><tr><td><a href="/profile/PopcornSecurity">PopcornSecurity</a></td><td>36251</td></tr></tbody></table>
<table><thead><tr><th>2014 Feb</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/TEO">TEO</a></td><td>89930</td></tr><tr><td><a href="/profile/rygar">rygar</a></td><td>37801</td></tr><tr><td><a href="/profile/hervas">hervas</a></td><td>33888</td></tr><tr><td><a href="/profile/the_pWn3R">the_pWn3R</a></td><td>31697</td></tr><tr><td><a href="/profile/kwisatz">kwisatz</a></td><td>29612</td></tr></tbody></table>
<table><thead><tr><th>2014 Mar</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/kwisatz">kwisatz</a></td><td>78161</td></tr><tr><td><a href="/profile/luzark">luzark</a></td><td>31241</td></tr><tr><td><a href="/profile/Jinx">Jinx</a></td><td>26617</td></tr><tr><td><a href="/profile/Snakeman2">Snakeman2</a></td><td>25056</td></tr><tr><td><a href="/profile/Mawekl">Mawekl</a></td><td>24658</td></tr></tbody></table>
<table><thead><tr><th>2014 Apr</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/Akorlith">Akorlith</a></td><td>52137</td></tr><tr><td><a href="/profile/sevenkplus">sevenkplus</a></td><td>25711</td></tr><tr><td><a href="/profile/madbat2">madbat2</a></td><td>23650</td></tr><tr><td><a href="/profile/Varg">Varg</a></td><td>22297</td></tr><tr><td><a href="/profile/rubiya">rubiya</a></td><td>22249</td></tr></tbody></table>
<table><thead><tr><th>2014 May</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/madbat2">madbat2</a></td><td>36420</td></tr><tr><td><a href="/profile/B0nk3rZ">B0nk3rZ</a></td><td>33691</td></tr><tr><td>unknown</td><td>29206</td></tr><tr><td><a href="/profile/vi0">vi0</a></td><td>22383</td></tr><tr><td><a href="/profile/the_pWn3R">the_pWn3R</a></td><td>21657</td></tr></tbody></table>
<table><thead><tr><th>2014 Jun</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/madbat2">madbat2</a></td><td>67194</td></tr><tr><td><a href="/profile/nurfed">nurfed</a></td><td>49090</td></tr><tr><td><a href="/profile/Proximus">Proximus</a></td><td>27594</td></tr><tr><td><a href="/profile/love0day">love0day</a></td><td>22705</td></tr><tr><td><a href="/profile/korkinsson">korkinsson</a></td><td>20250</td></tr></tbody></table>
<table><thead><tr><th>2014 Jul</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/skloj">skloj</a></td><td>64288</td></tr><tr><td><a href="/profile/kamzhik">kamzhik</a></td><td>41497</td></tr><tr><td><a href="/profile/Undr">Undr</a></td><td>40964</td></tr><tr><td><a href="/profile/New_LucA">New_LucA</a></td><td>39685</td></tr><tr><td><a href="/profile/love0day">love0day</a></td><td>38247</td></tr></tbody></table>
<table><thead><tr><th>2014 Aug</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/bruce30262">bruce30262</a></td><td>43343</td></tr><tr><td><a href="/profile/Anonr">Anonr</a></td><td>34591</td></tr><tr><td><a href="/profile/skloj">skloj</a></td><td>34159</td></tr><tr><td><a href="/profile/love0day">love0day</a></td><td>30783</td></tr><tr><td><a href="/profile/smirsk">smirsk</a></td><td>29367</td></tr></tbody></table>
<table><thead><tr><th>2014 Sep</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/sisyang">sisyang</a></td><td>44921</td></tr><tr><td><a href="/profile/madbat2">madbat2</a></td><td>43955</td></tr><tr><td><a href="/profile/Luis_1984">Luis_1984</a></td><td>41502</td></tr><tr><td><a href="/profile/gnumpty">gnumpty</a></td><td>31727</td></tr><tr><td><a href="/profile/encse">encse</a></td><td>26315</td></tr></tbody></table>
<table><thead><tr><th>2014 Oct</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/gnumpty">gnumpty</a></td><td>56022</td></tr><tr><td><a href="/profile/fuzzie">fuzzie</a></td><td>31903</td></tr><tr><td><a href="/profile/sinan">sinan</a></td><td>28198</td></tr><tr><td><a href="/profile/KnightKoroviev">KnightKoroviev</a></td><td>27112</td></tr><tr><td><a href="/profile/ggs2r00t">ggs2r00t</a></td><td>25083</td></tr></tbody></table>
<table><thead><tr><th>2014 Nov</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/s3Rious">s3Rious</a></td><td>29474</td></tr><tr><td><a href="/profile/sergiopesas">sergiopesas</a></td><td>28372</td></tr><tr><td><a href="/profile/Shrine">Shrine</a></td><td>23191</td></tr><tr><td><a href="/profile/redexel">redexel</a></td><td>22121</td></tr><tr><td><a href="/profile/gnumpty">gnumpty</a></td><td>19374</td></tr></tbody></table>
<table><thead><tr><th>2014 Dec</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/Meerkat">Meerkat</a></td><td>34478</td></tr><tr><td><a href="/profile/Rex_Mundi">Rex_Mundi</a></td><td>27140</td></tr><tr><td><a href="/profile/BlackTurtle">BlackTurtle</a></td><td>22874</td></tr><tr><td><a href="/profile/germanlm93">germanlm93</a></td><td>22523</td></tr><tr><td><a href="/profile/Santiagom">Santiagom</a></td><td>20968</td></tr></tbody></table>
<table><thead><tr><th>2015 Jan</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/martek">martek</a></td><td>48926</td></tr><tr><td><a href="/profile/perskee">perskee</a></td><td>47132</td></tr><tr><td><a href="/profile/dyroxyd">dyroxyd</a></td><td>40801</td></tr><tr><td><a href="/profile/nurfed">nurfed</a></td><td>31644</td></tr><tr><td><a href="/profile/Caesum">Caesum</a></td><td>30515</td></tr></tbody></table>
<table><thead><tr><th>2015 Feb</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/Caesum">Caesum</a></td><td>88281</td></tr><tr><td><a href="/profile/nurfed">nurfed</a></td><td>29189</td></tr><tr><td><a href="/profile/chitogee">chitogee</a></td><td>29055</td></tr><tr><td><a href="/profile/redexel">redexel</a></td><td>27753</td></tr><tr><td><a href="/profile/germanlm93">germanlm93</a></td><td>20941</td></tr></tbody></table>
<table><thead><tr><th>2015 Mar</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/yachoor">yachoor</a></td><td>15210</td></tr><tr><td><a href="/profile/juanescobar">juanescobar</a></td><td>12887</td></tr><tr><td><a href="/profile/ckclark">ckclark</a></td><td>12182</td></tr><tr><td><a href="/profile/chitogee">chitogee</a></td><td>10813</td></tr><tr><td><a href="/profile/Caesum">Caesum</a></td><td>6289</td></tr></tbody></table>
<table><thead><tr><th>2015 Apr</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/nevelezv">nevelezv</a></td><td>32011</td></tr><tr><td><a href="/profile/ckclark">ckclark</a></td><td>19616</td></tr><tr><td>unknown</td><td>16846</td></tr><tr><td><a href="/profile/Akorlith">Akorlith</a></td><td>15391</td></tr><tr><td><a href="/profile/Exploit">Exploit</a></td><td>14377</td></tr></tbody></table>
<table><thead><tr><th>2015 May</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/caos1986">caos1986</a></td><td>29291</td></tr><tr><td><a href="/profile/unicornFurnace">unicornFurnace</a></td><td>25282</td></tr><tr><td><a href="/profile/maf-ia">maf-ia</a></td><td>24309</td></tr><tr><td><a href="/profile/RichardBrook">RichardBrook</a></td><td>18202</td></tr><tr><td><a href="/profile/Vomitory">Vomitory</a></td><td>17471</td></tr></tbody></table>
<table><thead><tr><th>2015 Jun</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/benito255">benito255</a></td><td>67016</td></tr><tr><td><a href="/profile/martek">martek</a></td><td>37484</td></tr><tr><td><a href="/profile/juanda06">juanda06</a></td><td>36872</td></tr><tr><td><a href="/profile/mirmo">mirmo</a></td><td>29122</td></tr><tr><td><a href="/profile/nevelezv">nevelezv</a></td><td>26027</td></tr></tbody></table>
<table><thead><tr><th>2015 Jul</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/eseqrim">eseqrim</a></td><td>48643</td></tr><tr><td><a href="/profile/martek">martek</a></td><td>37257</td></tr><tr><td><a href="/profile/xire">xire</a></td><td>25987</td></tr><tr><td><a href="/profile/Akorlith">Akorlith</a></td><td>24953</td></tr><tr><td><a href="/profile/benito255">benito255</a></td><td>24038</td></tr></tbody></table>
<table><thead><tr><th>2015 Aug</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/DarkyAngel">DarkyAngel</a></td><td>49459</td></tr><tr><td><a href="/profile/MrStorm">MrStorm</a></td><td>43626</td></tr><tr><td><a href="/profile/einstein9918">einstein9918</a></td><td>22691</td></tr><tr><td><a href="/profile/vic511">vic511</a></td><td>21501</td></tr><tr><td><a href="/profile/jrying">jrying</a></td><td>18955</td></tr></tbody></table>
<table><thead><tr><th>2015 Sep</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/DarkyAngel">DarkyAngel</a></td><td>33123</td></tr><tr><td><a href="/profile/retr0">retr0</a></td><td>31410</td></tr><tr><td><a href="/profile/destiny2097">destiny2097</a></td><td>30536</td></tr><tr><td><a href="/profile/wooeong">wooeong</a></td><td>25156</td></tr><tr><td><a href="/profile/hidejc">hidejc</a></td><td>24388</td></tr></tbody></table>
<table><thead><tr><th>2015 Oct</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/rubiya">rubiya</a></td><td>28209</td></tr><tr><td><a href="/profile/Joon">Joon</a></td><td>22002</td></tr><tr><td><a href="/profile/kamel_louis">kamel_louis</a></td><td>16916</td></tr><tr><td><a href="/profile/cristiancol">cristiancol</a></td><td>16229</td></tr><tr><td><a href="/profile/santiagoholguing">santiagoholguing</a></td><td>15262</td></tr></tbody></table>
<table><thead><tr><th>2015 Nov</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/cubelover">cubelover</a></td><td>29729</td></tr><tr><td><a href="/profile/m00m00">m00m00</a></td><td>24502</td></tr><tr><td><a href="/profile/kumaus">kumaus</a></td><td>24466</td></tr><tr><td><a href="/profile/adm1nkyj">adm1nkyj</a></td><td>15941</td></tr><tr><td><a href="/profile/tynken0496">tynken0496</a></td><td>15902</td></tr></tbody></table>
<table><thead><tr><th>2015 Dec</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/sup3rm4n">sup3rm4n</a></td><td>58809</td></tr><tr><td><a href="/profile/maf-ia">maf-ia</a></td><td>23178</td></tr><tr><td><a href="/profile/thefinder">thefinder</a></td><td>16348</td></tr><tr><td><a href="/profile/do9dark">do9dark</a></td><td>15860</td></tr><tr><td><a href="/profile/bolofecal">bolofecal</a></td><td>15512</td></tr></tbody></table>
<table><thead><tr><th>2016 Jan</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/invik">invik</a></td><td>34730</td></tr><tr><td><a href="/profile/pedroysb">pedroysb</a></td><td>30782</td></tr><tr><td><a href="/profile/adm1nkyj">adm1nkyj</a></td><td>25873</td></tr><tr><td><a href="/profile/joizel">joizel</a></td><td>21988</td></tr><tr><td><a href="/profile/Ne0Lux-C1Ph3r">Ne0Lux-C1Ph3r</a></td><td>20653</td></tr></tbody></table>
<table><thead><tr><th>2016 Feb</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/integeruser">integeruser</a></td><td>29074</td></tr><tr><td><a href="/profile/cgn170">cgn170</a></td><td>23773</td></tr><tr><td><a href="/profile/TaRaSS">TaRaSS</a></td><td>21922</td></tr><tr><td><a href="/profile/MrCyph3r">MrCyph3r</a></td><td>21585</td></tr><tr><td><a href="/profile/Mr_Bert0ni">Mr_Bert0ni</a></td><td>19652</td></tr></tbody></table>
<table><thead><tr><th>2016 Mar</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/love0day">love0day</a></td><td>37712</td></tr><tr><td><a href="/profile/rubiya">rubiya</a></td><td>30723</td></tr><tr><td><a href="/profile/TaRaSS">TaRaSS</a></td><td>30553</td></tr><tr><td><a href="/profile/Milamber">Milamber</a></td><td>29645</td></tr><tr><td><a href="/profile/sljrobin">sljrobin</a></td><td>28325</td></tr></tbody></table>
<table><thead><tr><th>2016 Apr</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/jimeefr">jimeefr</a></td><td>20386</td></tr><tr><td><a href="/profile/dloser">dloser</a></td><td>19793</td></tr><tr><td><a href="/profile/jusb3">jusb3</a></td><td>17794</td></tr><tr><td><a href="/profile/N3W70N">N3W70N</a></td><td>15535</td></tr><tr><td><a href="/profile/freak_out">freak_out</a></td><td>15291</td></tr></tbody></table>
<table><thead><tr><th>2016 May</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/love0day">love0day</a></td><td>46267</td></tr><tr><td><a href="/profile/destiny2097">destiny2097</a></td><td>35589</td></tr><tr><td><a href="/profile/Sprundel">Sprundel</a></td><td>22942</td></tr><tr><td><a href="/profile/benito255">benito255</a></td><td>22854</td></tr><tr><td><a href="/profile/cyberguru">cyberguru</a></td><td>21684</td></tr></tbody></table>
<table><thead><tr><th>2016 Jun</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/kismet">kismet</a></td><td>44002</td></tr><tr><td><a href="/profile/humit">humit</a></td><td>28199</td></tr><tr><td><a href="/profile/cyberguru">cyberguru</a></td><td>26286</td></tr><tr><td><a href="/profile/plumssi">plumssi</a></td><td>23475</td></tr><tr><td><a href="/profile/afanasjef">afanasjef</a></td><td>18715</td></tr></tbody></table>
<table><thead><tr><th>2016 Jul</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/x2600">x2600</a></td><td>41297</td></tr><tr><td><a href="/profile/kismet">kismet</a></td><td>32466</td></tr><tr><td><a href="/profile/sisyang">sisyang</a></td><td>28572</td></tr><tr><td><a href="/profile/love0day">love0day</a></td><td>21006</td></tr><tr><td><a href="/profile/xoreaxeax">xoreaxeax</a></td><td>20320</td></tr></tbody></table>
<table><thead><tr><th>2016 Aug</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/x2600">x2600</a></td><td>26108</td></tr><tr><td><a href="/profile/jusb3">jusb3</a></td><td>25605</td></tr><tr><td><a href="/profile/Jarvis777">Jarvis777</a></td><td>23970</td></tr><tr><td><a href="/profile/bolofecal">bolofecal</a></td><td>21344</td></tr><tr><td><a href="/profile/sm62">sm62</a></td><td>20563</td></tr></tbody></table>
<table><thead><tr><th>2016 Sep</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/mwk">mwk</a></td><td>61426</td></tr><tr><td><a href="/profile/borysp">borysp</a></td><td>37449</td></tr><tr><td><a href="/profile/adami">adami</a></td><td>34279</td></tr><tr><td><a href="/profile/kazetkazet">kazetkazet</a></td><td>33933</td></tr><tr><td><a href="/profile/HackingGuy">HackingGuy</a></td><td>32556</td></tr></tbody></table>
<table><thead><tr><th>2016 Oct</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/palaxi0">palaxi0</a></td><td>24059</td></tr><tr><td><a href="/profile/kazetkazet">kazetkazet</a></td><td>24011</td></tr><tr><td><a href="/profile/Altran">Altran</a></td><td>22398</td></tr><tr><td><a href="/profile/pymac">pymac</a></td><td>17346</td></tr><tr><td><a href="/profile/Goso">Goso</a></td><td>14739</td></tr></tbody></table>
<table><thead><tr><th>2016 Nov</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/Goso">Goso</a></td><td>28455</td></tr><tr><td><a href="/profile/Xeron">Xeron</a></td><td>21457</td></tr><tr><td><a href="/profile/HackingGuy">HackingGuy</a></td><td>17992</td></tr><tr><td><a href="/profile/XStreamke">XStreamke</a></td><td>16885</td></tr><tr><td><a href="/profile/Rex_Mundi">Rex_Mundi</a></td><td>16157</td></tr></tbody></table>
<table><thead><tr><th>2016 Dec</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/Goso">Goso</a></td><td>29309</td></tr><tr><td><a href="/profile/sup3rm4n">sup3rm4n</a></td><td>25088</td></tr><tr><td><a href="/profile/jusb3">jusb3</a></td><td>24468</td></tr><tr><td><a href="/profile/spnow">spnow</a></td><td>22958</td></tr><tr><td><a href="/profile/taso">taso</a></td><td>19831</td></tr></tbody></table>
<table><thead><tr><th>2017 Jan</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/sasza8">sasza8</a></td><td>46581</td></tr><tr><td><a href="/profile/spnow">spnow</a></td><td>44720</td></tr><tr><td><a href="/profile/destiny2097">destiny2097</a></td><td>19642</td></tr><tr><td><a href="/profile/petr0v">petr0v</a></td><td>17973</td></tr><tr><td><a href="/profile/heartbits">heartbits</a></td><td>17806</td></tr></tbody></table>
<table><thead><tr><th>2017 Feb</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/Akorlith">Akorlith</a></td><td>28114</td></tr><tr><td><a href="/profile/crashdemons">crashdemons</a></td><td>22446</td></tr><tr><td><a href="/profile/Marvolo">Marvolo</a></td><td>22399</td></tr><tr><td><a href="/profile/jablonskim">jablonskim</a></td><td>21592</td></tr><tr><td><a href="/profile/tezeb">tezeb</a></td><td>20142</td></tr></tbody></table>
<table><thead><tr><th>2017 Mar</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/xseris">xseris</a></td><td>24396</td></tr><tr><td><a href="/profile/kazetkazet">kazetkazet</a></td><td>22136</td></tr><tr><td><a href="/profile/mlynekt">mlynekt</a></td><td>21072</td></tr><tr><td><a href="/profile/MuffinX">MuffinX</a></td><td>19476</td></tr><tr><td><a href="/profile/Akorlith">Akorlith</a></td><td>18729</td></tr></tbody></table>
<table><thead><tr><th>2017 Apr</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/Akorlith">Akorlith</a></td><td>30820</td></tr><tr><td><a href="/profile/jusb3">jusb3</a></td><td>28209</td></tr><tr><td><a href="/profile/mksecurity">mksecurity</a></td><td>25101</td></tr><tr><td><a href="/profile/adm1nkyj">adm1nkyj</a></td><td>24517</td></tr><tr><td><a href="/profile/JHSN">JHSN</a></td><td>22214</td></tr></tbody></table>
<table><thead><tr><th>2017 May</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/Envielox">Envielox</a></td><td>41298</td></tr><tr><td><a href="/profile/bolofecal">bolofecal</a></td><td>31720</td></tr><tr><td><a href="/profile/Akorlith">Akorlith</a></td><td>30063</td></tr><tr><td><a href="/profile/jusb3">jusb3</a></td><td>29521</td></tr><tr><td><a href="/profile/mlynekt">mlynekt</a></td><td>19901</td></tr></tbody></table>
<table><thead><tr><th>2017 Jun</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/peterisp">peterisp</a></td><td>53433</td></tr><tr><td><a href="/profile/MuffinX">MuffinX</a></td><td>46736</td></tr><tr><td><a href="/profile/jusb3">jusb3</a></td><td>32209</td></tr><tr><td><a href="/profile/yachoor">yachoor</a></td><td>29165</td></tr><tr><td><a href="/profile/Akorlith">Akorlith</a></td><td>27984</td></tr></tbody></table>
<table><thead><tr><th>2017 Jul</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/yachoor">yachoor</a></td><td>22189</td></tr><tr><td><a href="/profile/jusb3">jusb3</a></td><td>22107</td></tr><tr><td><a href="/profile/benito255">benito255</a></td><td>20429</td></tr><tr><td><a href="/profile/dienstag">dienstag</a></td><td>15580</td></tr><tr><td><a href="/profile/MuffinX">MuffinX</a></td><td>13528</td></tr></tbody></table>
<table><thead><tr><th>2017 Aug</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/benito255">benito255</a></td><td>35377</td></tr><tr><td><a href="/profile/thefinder">thefinder</a></td><td>29586</td></tr><tr><td><a href="/profile/destiny2097">destiny2097</a></td><td>23531</td></tr><tr><td><a href="/profile/plumssi">plumssi</a></td><td>21331</td></tr><tr><td><a href="/profile/jusb3">jusb3</a></td><td>21061</td></tr></tbody></table>
<table><thead><tr><th>2017 Sep</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/zen0c1de">zen0c1de</a></td><td>34832</td></tr><tr><td><a href="/profile/benito255">benito255</a></td><td>22173</td></tr><tr><td><a href="/profile/Mtuc">Mtuc</a></td><td>20502</td></tr><tr><td><a href="/profile/lykrysh">lykrysh</a></td><td>20346</td></tr><tr><td><a href="/profile/jusb3">jusb3</a></td><td>18755</td></tr></tbody></table>
<table><thead><tr><th>2017 Oct</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/x2600">x2600</a></td><td>29213</td></tr><tr><td><a href="/profile/benito255">benito255</a></td><td>28233</td></tr><tr><td><a href="/profile/jusb3">jusb3</a></td><td>16385</td></tr><tr><td><a href="/profile/Stockage">Stockage</a></td><td>16305</td></tr><tr><td><a href="/profile/AhnMo">AhnMo</a></td><td>14622</td></tr></tbody></table>
<table><thead><tr><th>2017 Nov</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/jusb3">jusb3</a></td><td>30956</td></tr><tr><td><a href="/profile/zen0c1de">zen0c1de</a></td><td>30198</td></tr><tr><td><a href="/profile/benito255">benito255</a></td><td>29759</td></tr><tr><td><a href="/profile/Akorlith">Akorlith</a></td><td>27474</td></tr><tr><td><a href="/profile/hundan">hundan</a></td><td>19288</td></tr></tbody></table>
<table><thead><tr><th>2017 Dec</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/Ne0Lux-C1Ph3r">Ne0Lux-C1Ph3r</a></td><td>34052</td></tr><tr><td><a href="/profile/benito255">benito255</a></td><td>14828</td></tr><tr><td><a href="/profile/Desogran">Desogran</a></td><td>12858</td></tr><tr><td><a href="/profile/bat86">bat86</a></td><td>10288</td></tr><tr><td><a href="/profile/Hul3man">Hul3man</a></td><td>9800</td></tr></tbody></table>
<table><thead><tr><th>2018 Jan</th></tr><tr><th>User</th><th>Scoregain</th></tr></thead><tbody><tr><td><a href="/profile/choiyd">choiyd</a></td><td>66633</td></tr><tr><td><a href="/profile/DrPres">DrPres</a></td><td>33636</td></tr><tr><td><a href="/profile/saiwa">saiwa</a></td><td>21815</td></tr><tr><td><a href="/profile/phacks">phacks</a></td><td>19844</td></tr><tr><td><a href="/profile/n3chto">n3chto</a></td><td>17407</td></tr></tbody></table>


</body>
</html>
