<div id="gwf_powered_by">
	<h1>GWF2 is using and powered by</h1>
	<hr/>
	<h2>Code in use:</h2>
	<h3>BSD Licensed</h3>
	<h4><a href="http://led24.de/iconset/">led24 Icons</a></h4>
	<h4><a href="http://www.ejeliot.com/pages/2">PhpCaptcha</a></h4>
	<!-- <div><a href="http://www.roonaan.nl/hotscripts/index.php?script=quickerubb.php">quickerubb</a></div>  -->
	<h3>GPL Licensed</h3>
	<h4><a href="#">GeSHi (??)</a></h4>
	<h4><a href="#">JPGraph (??)</a></h4>
	<!--  <div><a href="http://phplot.sourceforge.net/">phplot</a></div>  -->
	<!--  <div><a href="http://code.google.com/p/hyperlight/">hyperlight</a></div>  -->
	<hr/>
	<h2>Various</h2>
	<h4>Docs generated by <a href="http://www.stack.nl/~dimitri/doxygen/">Doxygen</a></h4>
</div>