<?php
return array(
	'Lernen Sie Spanisch in vierzehn Tagen',
	'Luke, ich bin Dein Vater',
	'Ich bin Gottes Liebling',
	'Ich denke, also bin ich?',
	'Nutze die Nacht',
	'Für immer ein Anfänger',
	'100 Kilo in 100 Tagen abnehmen',
	'Nennt mich Tim!',
	'Nanoschwalben und praktische Anwendungen',
	'Nylonfasern sind keine Sexobjekte',
	'Fahrstuhl zum Mond',
	'Japaner und Fehler',
	'Dubstep, Was kommt dann?',
	'Geistige Insolvenz im Mittelstand',
	'Die 31 besten Musikrichtungen',
	'Schlagerwahn bei jugendlichen Immigranten',
	'Helen Fischer nackt - Eine Fallstudie',
	'Java ist auch eine Programmiersprache',
	'Ich habe Dinge gesehen...',
	'Warum sollte er es löschen lassen?',
	'Schmutz auf Straßen und Beziehungen',
	'Pervers ist, was beiden nicht gefällt',
	'Die Twin Towers waren zu dritt',
	'Drei mal Drei ist Fünf',
	'Ein jeder ist seines eigenen Gliedes Schmück',
	'Ein jeder hat ein schmückes Glied',
	'Gliedmaßenverlängerung und Körperschmuck - Eine Rekapitulation',
	'Infisitimal rekursive Packalgorithmen II',
	'SAP - Ein Lebensgefühl',
	'Ortography in der Ornithologie',
	'Warum ich dieses Buch Schrieb',
	'Warum ich dieses Buch nicht geschrieben habe',
	'RC4 MOD 128 - Ein Rest bleibt',
	'Keine Freunde; Keine Feinde - Eine langweilige Biography',
	'Wenn ich Du wäre wäre ich lieber ich',
	'Was wäre wenn, Sesamstraße in 60 Minuten',
	'Kristallkugeln im Internet Relay Chat',
	'Critters - Die Laublosen',
	'Inspiration ist zur hälfte Fleiß',
	'GWF3 in einer Nußschale',
	'Die Gitarre ist ein Orcherster - und 100 andere dumme Sprüche',
	'Göthe war dichter',
	'E-mail spamming für aufstrebende Aufmerksamkeitsnymphomanen',
);
