<?php
$lang = array(
	'info' =>
		'You woke up for another gray day, and noticed that your bank account is empty as it is for months. You need some quick easy money, so you join some "darknet" irc channels in order to speak with people, who are able to give you some "not fully legal" job. Your new boss wants you to hack into a small bank infrastructure, and transfer money from one account to another. Easy job, huh?<br/>'.
		'<br/>'.
		'You drive with your van to the bank\'s main office, and setup your favourite wireless sniffing tool. Wow, it looks like they are using some WPA network. Let\'s sniff <a href="%1$s">some data</a>, and try to crack the WPA password with some dictionary attack.<br/>'.
		'<br/>'.
		'<br/>'.
		'Bug report: some older versions of ***crack-*g are unable to crack the password, be sure to use the latest (rc1 is known to be working).',
	'input' => 'Please enter the WPA key here',
	'bad' => 'Wrong',

	'info_login' =>
		'Now you can sniff the data through the air. '.
		'It looks like that the admininistrators are using PSA InsecurID to authenticate themselves to the PSA ACE server. '.
		'The good news are that they are using plain http connection. '.
		'Maybe the admins thought WPA is secure, so they don\'t need another layer of security. '.
		'Now you can do some easy arp cache poisoning, <a href="%1$s">sniff some authentication data</a> (username and the one time password generated by the PSA InsecurID token) and replay it to the authentication page.<br/>'.
		'You have 3 seconds to do that.<br/>'.
		'<br/>'.
		'submit the text to %2$s<br/>'.
		'Your timelimit is %3$s seconds.',

	'failed' => 'Login failed, invalid username or password.',
	'not_sniffed_yet' => 'Error: you have not sniffed the data yet.',

	'info_2' =>
		'Good job. Now you have succesfully uploaded the <a href="%1$s">new token data</a> for the victims bank account. '.
		'The base filename is the serial number for the token, and the seed (secret) is d4e3f9eb36c9ebf3. '.
		'Please note it is an older format of PSA InsecurID, the newer ones are using digitally signed XML files and longer seeds.<br/>'.
		'<br/>'.
		'After you have uploaded the new token data, you have to generate a valid one time password for that token for 27. of July, 2012 14:24 GMT+1',

	'info_final' =>
		'Good job, now you have logged in with that authentication information to the victim\'s bank account and can transfer some money to another. Nicely done. Your final mission is to spend the well deserved money you have received from your boss :)',
);
?>
