<?php
$lang = array(
	'en' => array(
		'help' => 'Usage: %CMD%. Print who has the real we-shirts, not those generated by the mud.',
		'shirts' => '1) lordOric, 2) gizmore, 3) grimskies, 4) Jander, 5) ztasiwk',
	),
);
$plugin = Dog::getPlugin();
$plugin->reply($plugin->lang('shirts'));
