<?php
/**
 * Some functions to get Infos like browser, OS, provider about the Surfer
 * @author spaceone
 * @version 1.0
 */
final class GWF_SF_SurferInfos { 

	private static $PROVIDER = array(
		array('Unknown', 'Unknown', 'unknown'),
		array('alicedsl.de' ,'Alice', 'alice'),
		array('aol.com' ,'AOL', 'aol'),
		array('einsundeins.de' ,'1&1', '1und1'),
		array('pools.arcor-ip.net' ,'Arcor', 'arcor'),
		array('t-dialin.net' ,'Telekom', 'telekom'),
		array('t-ipconnect.de' ,'Telekom', 'telekom'),
		array('vodafone.de' ,'Vodafone', 'vodafone'),
		array('d1-online.com' ,'T-Mobile', 'telekom'),
		array('superkabel.de' ,'Kabel Deutschland', 'kabeldeu'),
		array('ewe-ip-backbone.de' ,'EWE TEL', 'ewetel'),
		array('pppool.de' ,'Freenet', 'freenet'),
		array('hosteurope.de' ,'Host Europe', 'hosteurope'),
		array('kabelbw.de' ,'Kabel BW', 'kabelbw'),
		array('ish.de' ,'Unitymedia', 'unitymedia'),
		array('mediaways.net' ,'Telefonica', 'telefonica'),
		array('mnet-online.de' ,'M-net', 'mnet'),
		array('netcologne.de' ,'NetCologne', 'netcologne'),
		array('osnanet.de' ,'osnatel', 'osnatel'),
		array('qsc.de' ,'QSC', 'qsc'),
		array('sat-kabel-online.de' ,'Sat-Kabel', 'satkabel'),
		array('versanet.de' ,'Versatel', 'versatel'),
		array('viaginterkom.de' ,'ViagInterkom', 'viaginterkom'),		
	);
	
	private static $SYSTEM = array(
		array('Unknown', 'Unknown', 'unknown'),
		array("Windows 95", 'Windows 95', 'win95'),
		array("Windows 98", 'Windows 98', 'win98'),
		array("NT 4.0", 'Windows NT', 'winnt'),
		array("NT 5.0", 'Windows 2000', 'win2k'),
		array("NT 5.1", 'Windows XP', 'winxp'),
		array("NT 6.0", 'Windows Vista', 'winvista'),
		array("NT 6.1", 'Windows 7', 'win7'),
		'Windows',
		array("Ubuntu", 'Ubuntu', 'ubuntu'),
		array("Suse", 'OpenSuse', 'suse'),
		array("Debian", 'Debian', 'debian'),
		array("Gentoo", 'Gentoo', 'gentoo'),
		array("Mint", 'Linux Mint', 'mint'),
		array("Arch", 'Archlinux', 'arch'),
		'Linux',
		'Unix',
		'JVM',
		'FreeBSD',
		'BSD',
		'Mac OS',
		'Solaris',
		'SunOS',
		'IRIX',
		'Amiga OS',
		'OpenVMS',
		'BeOS',
		'Symbian OS',
		'Palm OS',
		'PlayStation Portable',
		'OS/2',
		'RISK OS',
		'Nintendo',
		'HP-UX',
		'AIX',
		'Plan 9',
		'RIM OS',
		'QNX',
		'MorphOS',
		'NetWare',
		'SCO',
		'SkyOS',
		'iPhone OS',
		'Haiku OS',
		'DangerOS',
		'Syllable',
		array('2x', '2X'),
		array('absolute', 'Absolute'),
		array('abuledu', 'AbulÉdu'),
		array('agilia', 'AgiliaLinux'),
		array('alinex', 'Alinex'),
		array('alinux', 'aLinux'),
		array('alpine', 'Alpine'),
		array('alt', 'ALT'),
		array('annyung', 'AnNyung'),
		array('antix', 'antiX'),
		array('apodio', 'APODIO'),
		array('aptosid', 'aptosid'),
		array('arch', 'Arch'),
		array('archbang', 'ArchBang'),
		array('archeos', 'ArcheOS'),
		array('arios', 'AriOS'),
		array('ark', 'Ark'),
		array('artistx', 'ArtistX'),
		array('asianux', 'Asianux'),
		array('astaro', 'Astaro'),
		array('asterisknow', 'AsteriskNOW'),
		array('asturix', 'Asturix'),
		array('auroraos', 'Aurora'),
		array('austrumi', 'AUSTRUMI'),
		array('avlinux', 'AV Linux'),
		array('backtrack', 'BackTrack'),
		array('baltix', 'Baltix'),
		array('bardinux', 'Bardinux'),
		array('bayanihan', 'Bayanihan'),
		array('berry', 'Berry'),
		array('biglinux', 'Big Linux'),
		array('blackpanther', 'blackPanther'),
		array('blag', 'BLAG'),
		array('blankon', 'BlankOn'),
		array('bodhi', 'Bodhi'),
		array('boss', 'BOSS'),
		array('brlix', 'BRLix'),
		array('bulinux', 'BU Linux'),
		array('burapha', 'Burapha'),
		array('cae', 'CAELinux'),
		array('caine', 'CAINE'),
		array('caixamagica', 'Caixa Mágica'),
		array('calculate', 'Calculate'),
		array('canaima', 'Canaima'),
		array('caos', 'Caos'),
		array('catix', 'Càtix'),
		array('ccux', 'CCux'),
		array('cdlinux', 'CDlinux'),
		array('censornet', 'CensorNet'),
		array('centos', 'CentOS'),
		array('chakra', 'Chakra'),
		array('clearos', 'ClearOS'),
		array('clonezilla', 'Clonezilla'),
		array('comfusion', 'Comfusion'),
		array('connochaet', 'Connochaet'),
		array('coyote', 'Coyote'),
		array('crunchbang', 'CrunchBang'),
		array('crux', 'CRUX'),
		array('ctkarch', 'CTKArch'),
		array('debian', 'Debian'),
		array('debris', 'Debris'),
		array('debxpde', 'DebXPde'),
		array('deepin', 'Deepin'),
		array('deft', 'DEFT'),
		array('desktopbsd', 'DesktopBSD'),
		array('devil', 'Devil'),
		array('digantel', 'DigAnTel'),
		array('doudou', 'DoudouLinux'),
		array('draco', 'Draco'),
		array('dragonflybsd', 'DragonFly'),
		array('dragora', 'Dragora'),
		array('dreamlinux', 'Dreamlinux'),
		array('dvl', 'DVL'),
		array('easypeasy', 'EasyPeasy'),
		array('edubuntu', 'Edubuntu'),
		array('ekaaty', 'Ekaaty'),
		array('elastix', 'Elastix'),
		array('elementary', 'elementary'),
		array('elive', 'Elive'),
		array('endian', 'Endian'),
		array('engarde', 'EnGarde'),
		array('epidemic', 'Epidemic'),
		array('estrellaroja', 'Estrella Roja'),
		array('esun', 'ESUN'),
		array('evinux', 'Evinux'),
		array('extix', 'ExTIX'),
		array('fedora', 'Fedora'),
		array('fermi', 'Fermi'),
		array('finnix', 'Finnix'),
		array('foresight', 'Foresight'),
		array('freebsd', 'FreeBSD'),
		array('freenas', 'FreeNAS'),
		array('frenzy', 'Frenzy'),
		array('frugalware', 'Frugalware'),
		array('fuduntu', 'Fuduntu'),
		array('fuguita', 'FuguIta'),
		array('fusion', 'Fusion'),
		array('geexbox', 'GeeXboX'),
		array('gentoo', 'Gentoo'),
		array('gentoox', 'Gentoox'),
		array('ghostbsd', 'GhostBSD'),
		array('gibraltar', 'Gibraltar'),
		array('gnacktrack', 'GnackTrack'),
		array('gnewsense', 'gNewSense'),
		array('gnobsd', 'GNOBSD'),
		array('gnustep', 'GNUstep'),
		array('gparted', 'GParted'),
		array('greenie', 'Greenie'),
		array('grml', 'Grml'),
		array('guadalinex', 'Guadalinex'),
		array('hacao', 'Hacao'),
		array('helix', 'Helix'),
		array('honeywall', 'Honeywall'),
		array('idms', 'IDMS'),
		array('imagicos', 'iMagic'),
		array('imagineos', 'Imagineos'),
		array('incognito', 'Incognito'),
		array('inquisitor', 'Inquisitor'),
		array('insigne', 'Insigne'),
		array('ipcop', 'IPCop'),
		array('ipfire', 'IPFire'),
		array('jibbed', 'Jibbed'),
		array('jolinux', 'JoLinux'),
		array('jolios', 'Joli OS'),
		array('k12linux', 'K12Linux'),
		array('kdemar', 'kademar'),
		array('kahelos', 'KahelOS'),
		array('kanotix', 'KANOTIX'),
		array('karoshi', 'Karoshi'),
		array('kiwi', 'Kiwi'),
		array('knoppel', 'Knoppel'),
		array('knoppix', 'KNOPPIX'),
		array('knosciences', 'KnoSciences'),
		array('kongoni', 'Kongoni'),
		array('kororaa', 'Kororaa'),
		array('kubuntu', 'Kubuntu'),
		array('kwort', 'Kwort'),
		array('legacy', 'Legacy'),
		array('lfs', 'LFS'),
		array('linex', 'LinEx'),
		array('linhes', 'LinHES'),
		array('linpus', 'Linpus'),
		array('linuxconsole', 'LinuxConsole'),
		array('linuxeducd', 'Linux-EduCD'),
		array('linuxgamers', 'linuX-gamers'),
		array('linuxtle', 'LinuxTLE'),
		array('litrix', 'Litrix'),
		array('livecdrouter', 'LiveCD Router'),
		array('lliurex', 'LliureX'),
		array('lubuntu', 'Lubuntu'),
		array('lunar', 'Lunar'),
		array('monowall', 'm0n0wall'),
		array('macpup', 'Macpup'),
		array('madbox', 'Madbox'),
		array('mageia', 'Mageia'),
		array('magic', 'Magic'),
		array('mandriva', 'Mandriva'),
		array('mangaka', 'Mangaka'),
		array('max', 'MAX'),
		array('mcnlive', 'MCNLive'),
		array('meego', 'MeeGo'),
		array('mepis', 'MEPIS'),
		array('midnightbsd', 'MidnightBSD'),
		array('milax', 'MilaX'),
		array('minino', 'MiniNo'),
		array('minix', 'MINIX'),
		array('mint', 'Mint'),
		array('miracle', 'Miracle'),
		array('miros', 'MirOS'),
		array('moblin', 'Moblin'),
		array('molinux', 'MoLinux'),
		array('momonga', 'Momonga'),
		array('monomaxos', 'Monomaxos'),
		array('moonos', 'moonOS'),
		array('musix', 'Musix'),
		array('myrinix', 'Myrinix'),
		array('mythbuntu', 'Mythbuntu'),
		array('mythdora', 'MythDora'),
		array('natures', 'Nature\'s'),
		array('neoshine', 'NeoShine'),
		array('nepalinux', 'NepaLinux'),
		array('netbsd', 'NetBSD'),
		array('netrunner', 'Netrunner'),
		array('netsecl', 'NetSecL'),
		array('nexenta', 'Nexenta'),
		array('nexentastor', 'NexentaStor'),
		array('niigata', 'Niigata'),
		array('nimblex', 'NimbleX'),
		array('nova', 'Nova'),
		array('novell', 'Novell SLE'),
		array('nst', 'NST'),
		array('nutyx', 'NuTyX'),
		array('ojuba', 'Ojuba'),
		array('olpc', 'OLPC'),
		array('omoikane', 'Omoikane'),
		array('onet', 'O-Net'),
		array('openbsd', 'OpenBSD'),
		array('openfiler', 'Openfiler'),
		array('openindiana', 'OpenIndiana'),
		array('openmamba', 'openmamba'),
		array('suse', 'openSUSE'),
		array('openwall', 'Openwall'),
		array('ophcrack', 'Ophcrack'),
		array('oracle', 'Oracle'),
		array('paipix', 'PAIPIX'),
		array('paldo', 'paldo'),
		array('papug', 'PapugLinux'),
		array('pardus', 'Pardus'),
		array('parsix', 'Parsix'),
		array('partedmagic', 'Parted Magic'),
		array('pcbsd', 'PC-BSD'),
		array('pclinuxos', 'PCLinuxOS'),
		array('pcos', 'PC/OS'),
		array('pelicanhpc', 'PelicanHPC'),
		array('pentoo', 'Pentoo'),
		array('peppermint', 'Peppermint'),
		array('pfsense', 'pfSense'),
		array('phayoune', 'Phayoune'),
		array('pinguy', 'Pinguy'),
		array('plamo', 'Plamo'),
		array('pld', 'PLD'),
		array('plop', 'Plop'),
		array('porteus', 'Porteus'),
		array('poseidon', 'Poseidon'),
		array('pqui', 'pQui'),
		array('privatix', 'Privatix'),
		array('puppy', 'Puppy'),
		array('puredyne', 'Puredyne'),
		array('pureos', 'PureOS'),
		array('qimo', 'Qimo'),
		array('qomo', 'Qomo'),
		array('quirky', 'Quirky'),
		array('redflag', 'Red Flag'),
		array('redhat', 'Red Hat'),
		array('redwall', 'redWall'),
		array('resulinux', 'Resulinux'),
		array('rip', 'RIPLinuX'),
		array('rockscluster', 'Rocks Cluster'),
		array('rpath', 'rPath'),
		array('runtu', 'Runtu'),
		array('sabayon', 'Sabayon'),
		array('sabily', 'Sabily'),
		array('saline', 'SalineOS'),
		array('salix', 'Salix'),
		array('samity', 'SAMity'),
		array('satux', 'Satux'),
		array('schillix', 'SchilliX'),
		array('scientific', 'Scientific'),
		array('securepoint', 'Securepoint'),
		array('skolelinux', 'Skolelinux'),
		array('slackintosh', 'Slackintosh'),
		array('slackware', 'Slackware'),
		array('slampp', 'SLAMPP'),
		array('slitaz', 'SliTaz'),
		array('smeserver', 'SME Server'),
		array('smoothwall', 'SmoothWall'),
		array('sms', 'SMS'),
		array('sol', 'SoL'),
		array('solaris', 'Solaris'),
		array('sorcerer', 'Sorcerer'),
		array('sourcemage', 'Source Mage'),
		array('startcom', 'StartCom'),
		array('std', 'STD'),
		array('stresslinux', 'StressLinux'),
		array('stux', 'STUX'),
		array('sulix', 'SuliX'),
		array('supergamer', 'SuperGamer'),
		array('superos', 'Super OS'),
		array('suriyan', 'Suriyan'),
		array('syllable', 'Syllable'),
		array('systemrescue', 'SystemRescue'),
		array('t2', 'T2'),
		array('tfm', 'TFM'),
		array('thinstation', 'Thinstation'),
		array('tinycore', 'Tiny Core'),
		array('tinyme', 'TinyMe'),
		array('toorox', 'Toorox'),
		array('topologilinux', 'Topologilinux'),
		array('toutou', 'Toutou'),
		array('trinity', 'Trinity'),
		array('trisquel', 'Trisquel'),
		array('trixbox', 'trixbox'),
		array('tuquito', 'Tuquito'),
		array('turbolinux', 'Turbolinux'),
		array('turnkey', 'TurnKey'),
		array('uberstudent', 'UberStudent'),
		array('ubuntu', 'Ubuntu'),
		array('ubunturescue', 'Ubuntu Rescue'),
		array('ubuntustudio', 'Ubuntu Studio'),
		array('uhu', 'UHU-Linux'),
		array('ulteo', 'Ulteo'),
		array('ultimate', 'Ultimate'),
		array('unity', 'Unity'),
		array('untangle', 'Untangle'),
		array('ubuntupr', 'UPR'),
		array('userful', 'Userful'),
		array('ututo', 'UTUTO'),
		array('vector', 'Vector'),
		array('venenux', 'VENENUX'),
		array('vine', 'Vine'),
		array('vinux', 'Vinux'),
		array('vlos', 'VLOS'),
		array('vmknoppix', 'VMKnoppix'),
		array('vnlinux', 'VNLinux'),
		array('vortexbox', 'VortexBox'),
		array('vyatta', 'Vyatta'),
		array('wattos', 'wattOS'),
		array('webconverger', 'Webconverger'),
		array('wifislax', 'Wifislax'),
		array('xange', 'Xange'),
		array('xpud', 'xPUD'),
		array('xubuntu', 'Xubuntu'),
		array('yellowdog', 'Yellow Dog'),
		array('ylmf', 'Ylmf'),
		array('yoper', 'Yoper'),
		array('zencafe', 'Zencafe'),
		array('zentyal', 'Zentyal'),
		array('zenwalk', 'Zenwalk'),
		array('zeroshell', 'Zeroshell'),
		array('zevenos', 'ZevenOS'),
		array('zorin', 'Zorin'),
	);
	private static $BROWSER = array(
		array('Unknown', 'Unknown', 'unknown'),
		array('Firefox/4', 'Firefox4', 'ff4'),
		array('Firefox/3', 'Firefox3', 'ff3'),
		array('Firefox/5', 'Firefox5', 'ff5'),
		array('Firefox', 'Firefox', 'ff'),
		array('Opera', 'Opera', 'opera'),
		array('Chromium', 'Chromium', 'chromium'),
		array('Chrome', 'Google-Chrome', 'chrome'),
		array('MSIE 9.0', 'Internet Explorer 9', 'ie9'),
		array('MSIE 8.0', 'Internet Explorer 8', 'ie8'),
		array('MSIE 7.0', 'Internet Explorer 7', 'ie7'),
		array('MSIE 6.0', 'Internet Explorer 6', 'ie6'),
		array('MSIE 5.0', 'Internet Explorer 5', 'ie5'),
		array('MSIE 5.5', 'Internet Explorer 5.5', 'ie5'),
		array('MSIE', 'Internet Explorer', 'ie'),
		array('Safari', 'Safari', 'safari'),
		array('Lynx', 'Lynx', 'lynx'),
		array('WebTV', 'WebTV', 'webtv'),
		array('Konqueror', 'Konqueror', 'konqueror'),
		array('Mozilla', 'Mozilla', 'mozilla'),
		array('w3m', 'w3m', 'w3m'),
	);

	public static function get_hostname($default = false) {
		return isset($_SERVER['REMOTE_ADDR']) ? htmlspecialchars(getHostByAddr($_SERVER['REMOTE_ADDR'])) : $default;
	}
	public static function get_useragent($default = false) {
	//	if(SF_HackingAttemp::SERVER_manipulation($_SERVER['HTTP_USER_AGENT'])) return $default;
		return isset($_SERVER['HTTP_USER_AGENT']) ? htmlspecialchars($_SERVER['HTTP_USER_AGENT']) : $default;
	}
	public static function get_ipaddress($default = '127.0.0.1') {
		return isset($_SERVER['REMOTE_ADDR']) ? $_SERVER['REMOTE_ADDR'] : $default;
	}
	public static function get_referer($default = false) {
	//	if(SF_HackingAttemp::SERVER_manipulation($_SERVER['HTTP_REFERER'])) return $default;
		return isset($_SERVER['HTTP_REFERER']) ? htmlspecialchars($_SERVER['HTTP_REFERER']) : $default;
	}
	//public static function get_forwarder() { return GWF_IP6::forwarder(); }
	public static function get_details($search, $subj, $type = 1, $default = false) {

		if( !$search ) return $default;

		foreach($subj as $detail) {
			if(is_array($detail)) {
				if(stristr($search, $detail[0])) {
					return array_key_exists($type, $detail) ? $detail[$type] : $detail[1];
				}	
			} elseif(stristr($search, $detail)) {
				return $detail;
			}
		}
		return $subj[0][$type];
	
	}
	public static function get_provider($type = 1, $cmp = NULL) { 
		$detail = self::get_details(self::get_hostname(), self::$PROVIDER, $type); 
		return $cmp == NULL ? $detail : $cmp === $detail;
	}
	public static function get_operatingsystem($type = 1, $cmp = NULL) { 
		$detail = self::get_details(self::get_useragent(), self::$SYSTEM, $type); 
		return $cmp == NULL ? $detail : $cmp === $detail;
	}
	public static function get_browser($type = 1, $cmp = NULL) { 
		$detail = self::get_details(self::get_useragent(), self::$BROWSER, $type);
		return $cmp == NULL ? $detail : $cmp === $detail;
	}

	// public static function save_referer() { return;	}

}

?>
